### ISSUE TITLE
Dropdown for languages

### ISSUE THREAD

**Issue by SketchNI** [whitep4nth3r/randomcodegenerator.lol#46]
As the list of languages grows, the buttons will get unwieldy. They are getting that way already.
![image](https://user-images.githubusercontent.com/11874768/113698063-f8b3ea00-96cb-11eb-878b-a3fe1426716f.png)

I propose something @whitep4nth3r mentioned on stream yesterday (5th Apr 2021) which is a dropdown for languages. But by taking it one step further we can introduce a second dropdown purely for lols which is a list of esoteric languages such as LOLCODE, Brainfuck, Rockstar and the like.

**Comment by lukeocodes** [comment]
I think adding more and more buttons just adds to the ridiculousness
