### ISSUE TITLE
getRandomLogLine() is not language agnostic

### ISSUE THREAD

**Issue by jwalter** [whitep4nth3r/randomcodegenerator.lol#49]
A few of the options returned by getRandomLogLine() are not valid in all languages:
"**********"
"[object Object]"
"NaN"

Using these in for example Java or Kotlin would lead to compilation errors. Should this be considered a feature or a bug?

**Comment by isabellabrookes** [comment]
I'm pretty sure they should all be strings - I understand that they may not be language agnostic though.

**Comment by whitep4nth3r** [comment]
I have no idea. It was just funny at the time.

**Comment by whitep4nth3r** [comment]
I don't think those are valid in any language to be honest!
