### ISSUE TITLE
Add GitHub logo mark in the top right corner of the page

### ISSUE THREAD

**Issue by whitep4nth3r** [whitep4nth3r/randomcodegenerator.lol#62]

**Comment by OussamaSALAHOUELHADJ** [comment]
Hey @whitep4nth3r I can work on this issue, can you tell me more about it and assign it to me.

**Comment by whitep4nth3r** [comment]
Hey Oussama, I've decided this issue isn't relevant anymore now that the code is powered by an npm package.
